language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk
  - Squeak-5.0
  - Squeak-4.6
  - Squeak-4.5

  - Pharo-alpha
  - Pharo-stable
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0

smalltalk_config: .smalltalk.ston

os:
  - linux
  - osx

install:
  # Move cache directory if it exists
  - if [[ -d "${SMALLTALK_CI_CACHE}" ]]; then mv $SMALLTALK_CI_CACHE "$(pwd)"; fi
  # Make sure to use smalltalkCI from this branch
  - if [[ -n "${SMALLTALK_CI_HOME}" ]]; then rm -rf $SMALLTALK_CI_HOME && ln -s "$(pwd)" $SMALLTALK_CI_HOME; fi

script:
  - $SMALLTALK_CI_HOME/run.sh --debug && $SMALLTALK_CI_HOME/tests/fail_test.sh

matrix:
  include:
    # Bash tests
    - language: bash
      smalltalk:
      sudo: false
      script: bash tests/all_tests.sh

    # GemStone Linux builds
    - smalltalk: GemStone-3.3.0
      os: linux
      env: GSCI_CLIENTS="Pharo-5.0 Pharo-4.0 Pharo-3.0" GSCI_DEVKIT_BRANCH=dev
    - smalltalk: GemStone-3.3.0
      os: linux
      env: GSCI_DEVKIT_BRANCH=dev    # only use for development --- leave until https://github.com/GsDevKit/GsDevKit_home/issues/93 merged
    - smalltalk: GemStone-3.3.0
      os: linux
      env: GSCI_DEVKIT_BRANCH=master # uncover any issues using new SmalltalkCI with old GsDevKit_home
      cache:
        directories:
          - $SMALLTALK_CI_CACHE      # don't use dependency cache with nonstandard GSCI_DEVKIT_BRANCH
    - smalltalk: GemStone-3.2.14
      os: linux
#      env: GSCI_DEVKIT_BRANCH=dev   # only use for development
      cache:
        directories:
          - $SMALLTALK_CI_CACHE      # don't use dependency cache with nonstandard GSCI_DEVKIT_BRANCH
    - smalltalk: GemStone-3.1.0.6
      os: linux
#      env: GSCI_DEVKIT_BRANCH=dev   # only use for development
      cache:
        directories:
          - $SMALLTALK_CI_CACHE      # don't use dependency cache with nonstandard GSCI_DEVKIT_BRANCH
    # GemStone OS X builds
    - smalltalk: GemStone-3.3.0
      os: osx
##      env: GSCI_DEVKIT_BRANCH=dev  # only use for development
#    - smalltalk: GemStone-3.2.14
#      os: osx
##      env: GSCI_DEVKIT_BRANCH=dev  # only use for development
#    - smalltalk: GemStone-3.1.0.6
#      os: osx
##      env: GSCI_DEVKIT_BRANCH=dev  # only use for development
