sudo: false

env:
  global:
    - BASELINE=SWTDemo
  matrix:
    - SMALLTALK="Squeak-Trunk"
    - SMALLTALK="Squeak-5.0"
    - SMALLTALK="Squeak-4.6"
    - SMALLTALK="Squeak-4.5"

    - Pharo-5.0
    - Pharo-4.0
    - Pharo-3.0

os:
  - linux
  - osx

addons:
  apt:
    packages:
    # 32-bit VM
    - libc6:i386
    # UUIDPlugin
    - libuuid1:i386

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O filetreeCI.zip https://github.com/fniephaus/filetreeCI/archive/dev.zip
   - unzip -q filetreeCI.zip
   - cd filetreeCI-*
   - source env_vars

script: $FILETREE_CI_HOME/run.sh