sudo: true

env:
  global:
    - BASELINE=SWTDemo
  matrix:
    - SMALLTALK="Squeak-Trunk"
    - SMALLTALK="Squeak-5.0"
    - SMALLTALK="Squeak-4.6"
    - SMALLTALK="Squeak-4.5"

    - SMALLTALK="Pharo-alpha"
    - SMALLTALK="Pharo-stable"
    - SMALLTALK="Pharo-5.0"
    - SMALLTALK="Pharo-4.0"
    - SMALLTALK="Pharo-3.0"

    - SMALLTALK="GemStone-3.2.7"
    - SMALLTALK="GemStone-3.2.0"
    - SMALLTALK="GemStone-3.1.0.6"
    - SMALLTALK="GemStone-3.1.0.2"
    - SMALLTALK="GemStone-3.0.1"
    - SMALLTALK="GemStone-2.4.6"
    - SMALLTALK="GemStone-2.4.5"
    - SMALLTALK="GemStone-2.4.4.1"

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O smalltalkCI.zip https://github.com/hpi-swa/smalltalkCI/archive/dev.zip
   - unzip -q smalltalkCI.zip
   - cd smalltalkCI-*
   - source env_vars

script: $SMALLTALK_CI_HOME/run.sh
